import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Image from '../components/ui/image';
import LOGO_apitech_amari05 from "../assets/LOGO_apitech_amari05.svg";
import MobileMockup from "../assets/MobileMockup.png";
import app_Store from "../assets/app_Store.png";
import Play_Store from "../assets/Play_Store.png";
//import linea_punteada from "../assets/linea_punteada-05.svg";//--
const ApiTechLanding = () => {
    return (_jsx("div", { className: "elementor elementor-1362 p-8 relative", children: _jsxs("div", { className: "max-w-7xl mx-auto flex flex-col lg:flex-row", children: [_jsxs("div", { className: "w-full lg:w-1/2 space-y-8 lg:text-left text-center relative z-10", children: [_jsx(Image, { src: LOGO_apitech_amari05, width: 300, height: 85, alt: "Apitech Logo" }), _jsxs("h1", { className: "font-bold text-[#FFA500] text-[28px] sm:text-[32px] md:text-[40px] lg:text-[48px] mb-6 px-2 fond-text-russo - 55px", children: ["GESTIONA Y MONITOREA", _jsx("span", { className: "text-[#FFC91C]", children: " TUS COLMENAS " }), "DESDE CUALQUIER LUGAR."] }), _jsx(Image, { src: MobileMockup, width: 700, height: 755, alt: "Mobile Mockup", className: "lg:hidden mx-auto -mt-4" }), _jsx("p", { className: "text-white mb-16 max-w-lg mx-auto lg:mx-0", children: "Registra, monitorea y aprende todo lo necesario para maximizar el rendimiento de tus apiarios con sensores avanzados y gu\u00EDas expertas." }), _jsxs("div", { className: "flex flex-col lg:flex-row lg:items-center lg:space-x-4 mb-4 lg:text-left text-center", children: [_jsxs("div", { className: "flex justify-center lg:justify-start space-x-4 mb-4 lg:mb-0", children: [_jsx("a", { href: "#", className: "transform hover:scale-105 transition-transform", children: _jsx(Image, { src: Play_Store, width: 205, height: 70, alt: "Play Store" }) }), _jsx("a", { href: "#", className: "transform hover:scale-105 transition-transform", children: _jsx(Image, { src: app_Store, width: 205, height: 70, alt: "App Store" }) })] }), _jsxs("div", { className: "text-sm lg:ml-4 lg:mt-0 mt-4", children: [_jsx("p", { children: "* Prueba gratis." }), _jsx("p", { children: "M\u00E1ximo 5 colmenas." })] })] })] }), _jsx("div", { className: "hidden lg:block w-full lg:w-1/2 text-left relative z-10 -mt-8", children: _jsx(Image, { src: MobileMockup, width: 700, height: 755, alt: "Mobile Mockup", className: "transform hover:rotate-1 transition-transform relative", style: { bottom: '-20px' } }) })] }) }));
};
export default ApiTechLanding;
